name: auto-update

on:
  schedule:
    - cron: "0 0 * * *"
  push: {}

permissions:
  contents: write # to commit
  id-token: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pip install
        run: pip install --break-system-packages -r requirements.txt
      - name: Fetch schedules
        run: python fetch_schedules.py
      - name: Configure AWS Credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/kabu-json-github-actions-role
          role-session-name: github-actions-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}
      - name: Upload to S3
        run: |
          aws s3 cp schedules.json s3://kabu-json-public-static-data-bucket/kabu-json-kessan-schedules/v1/schedules.json --content-type application/json
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schedules.json --force
          git commit -m "Update json files $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "No changes to commit"
